#/usr/bin/env bash

all: README.md

README.md: GuessingGame.sh
	touch README.md
	echo "# GuessingGame" > README.md
	echo $$(date) >> README.md
	echo "  \n" >> README.md
	wc -l GuessingGame.sh | egrep -o "[0-9]+" >> README.md
clean:
	rm README.md
© 2020 GitHub, Inc.
